service: weather_app
image: invalidusrname/weather_app

servers:
  web:
    hosts:
      - um580
    proxy:
      ssl_redirect: false
      app_port: 3000
      host: weather.invalid8.com
      healthcheck:
        path: /up

ssh:
  user: app

registry:
  server: localhost:5555

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    RAILS_LOG_LEVEL: info

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - /home/app/weather_app/storage:/rails/storage

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

builder:
  arch: amd64
  args:
    GIT_SHA: ${KAMAL_VERSION:-$(git rev-parse HEAD)}
